# Generated by Django 4.2.20 on 2025-03-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='content',
        ),
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.AddField(
            model_name='book',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='tts/', verbose_name='음성 파일'),
        ),
        migrations.AddField(
            model_name='book',
            name='author_info',
            field=models.TextField(blank=True, verbose_name='작가 정보 (AI 생성)'),
        ),
        migrations.AddField(
            model_name='book',
            name='author_works',
            field=models.TextField(blank=True, verbose_name='작가 대표작 목록 (AI 생성)'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='books/', verbose_name='커버 이미지'),
        ),
        migrations.AddField(
            model_name='book',
            name='customer_review_rank',
            field=models.FloatField(blank=True, null=True, verbose_name='회원 리뷰 평점'),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default=1, verbose_name='설명'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, verbose_name='저자'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, verbose_name='도서 제목'),
        ),
    ]
