# Generated by Django 4.2.20 on 2025-04-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_content_remove_book_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='작가 프로필 이미지'),
        ),
        migrations.AlterField(
            model_name='book',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='tts/', verbose_name='Voice File'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='books/', verbose_name='Cover image'),
        ),
        migrations.AlterField(
            model_name='book',
            name='customer_review_rank',
            field=models.FloatField(blank=True, null=True, verbose_name='Customer review rank'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
