# Generated by Django 4.2.20 on 2025-04-11 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_interest_alter_user_monthly_reading_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='interest',
            new_name='interests',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='monthly_reading_time',
            new_name='weekly_reading',
        ),
    ]
