# Generated by Django 4.2.20 on 2025-04-25 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='user',
        ),
    ]
